CHARACTER_STATS = {
    "Feats": {
        "type": "bullet",
        "content": [
            "Mentored and coached teams nationwide and globally to hone technical and non-technical skills.",
            "Orchestrated the adoption of organizational technology.",
            "Created sophisticated data generation modules to populate transient environments with data that mimics production.",
            "Devised serverless lambdas for distributed data processing.",
            "Engineered Continuous Deployment pipelines for seamless and frequent software updates.",
            "Established and implemented pipeline quality gates to guarantee confidence in Continuous Deployment pipelines.",
            "Conceptualized, launched, and currently maintain web applications for small-scale enterprises.",
            "Decreased the time for build validation feedback loops from 3 days to 5 minutes.",
            "Led initiatives to raise code coverage at various levels from 2% to above 80%.",
            "Standardized approaches to unit, integration, and end-to-end testing.",
        ]
    },
    "Abilities": {
        "type": "badge",
        "content": [
            "Programming",
            "Front End Development",
            "Back End Development",
            "Full-Stack Development",
            "Web Services and APIs",
            "Containerization and Orchestration",
            "Serverless Computing",
            "Object-Oriented Design and Development",
            "Database Design and Management",
            "Cloud Computing",
            "DevOps",
            "Agile Methodologies",
            "Git and Version Control",
            "Technical Writing and Documentation",
            "Quality Engineering",
            "Software Consulting",
            "Peer Reviews",
        ]
    },
    "Skills": {
        "type": "badge",
        "content": [
            "Leadership",
            "Coaching and Mentoring",
            "Continuous Integration",
            "Continuous Deployment",
            "Continuous Testing",
            "HTML",
            "CSS",
            "JavaScript",
            "TypeScript",
            "Python",
            "Ruby",
            "Jinja",
            "GDScript"
            "Django",
            "Pytest",
            "Flask",
            "Rails",
            "Rspec",
            "Cypress",
            "MongoDB",
            "PostgreSQL",
            "Digital Ocean",
            "AWS",
            "Google Cloud",
            "REST",
            "GraphQL",
            "Docker",
            "Software Testing",
            "Scrum",
            "Kanban",
            "Git",
            "GitHub Actions",
            "Bitbucket Pipelines",
            "Jest"
            "React",
            "React Testing Library",
            "NUnit",
            "Behavior Driven Development",
            "Test Driven Development",
        ]
    },
    "Traits": {
        "type": "badge",
        "content": [
            "Innovative",
            "Agile",
            "Analytical",
            "Resourceful",
            "Creative",
            "Detail-oriented",
            "Decisive",
            "Curious",
            "Resilient",
            "Adaptable",
            "Persistent",
            "Efficient",
            "Communicative",
            "Strategic",
            "Passionate"
        ]
    }
}
